# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='year',
            field=models.CharField(default='null', max_length=4),
            preserve_default=False,
        ),
    ]
