# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_collection_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='watched',
            field=models.CharField(default='f', max_length=1),
            preserve_default=False,
        ),
    ]
